//! Iceberg v2 Table Format Export
//!
//! Implements on-demand Iceberg v2 spec-compliant export for RockDuck.
//! Data files are stored as Vortex (Arrow IPC) — DuckDB reads them natively
//! via its core `vortex` extension.
//!
//! Architecture: two-layer design
//!
//! - **Native manifest** (hot path): stored as bincode in RocksDB CF "iceberg_manifest",
//!   updated on every compaction commit. Low overhead, crash-safe.
//! - **Iceberg spec artifacts** (on-demand): generated by `export_to_iceberg()` into a
//!   target directory — metadata.json + manifest-list Avro + manifest Avro + version-hint.

pub mod translate;
pub mod avro_writer;
pub mod catalog;
pub mod export;

use std::collections::HashMap;
use serde::{Deserialize, Serialize};
use bincode_next::{Encode, Decode};

/// Vortex file format identifier used in Iceberg manifest.
pub const VORTEX_FORMAT: &str = "VORTEX";

/// Sort order ID assigned to the default primary-key ascending order.
pub const DEFAULT_SORT_ORDER_ID: i32 = 1;

/// Iceberg Export manifest — the native in-RocksDB representation of an Iceberg snapshot.
///
/// This struct is serialised via bincode and stored in RocksDB column family
/// `iceberg_manifest`. It is NOT the Iceberg spec JSON; it is RockDuck's own
/// internal manifest format that maps directly onto Iceberg concepts.
///
/// On `export_to_iceberg()` we translate this into spec-compliant JSON and Avro.
#[derive(Debug, Clone, Serialize, Deserialize, Encode, Decode)]
pub struct IcebergExport {
    /// UUID that identifies this table across exports.
    pub table_uuid: String,
    /// Monotonically increasing snapshot ID (Iceberg `snapshot_id`).
    pub snapshot_id: i64,
    /// Data sequence number (Iceberg `sequence_number`).
    pub sequence_number: i64,
    /// Parent snapshot ID, if any.
    pub parent_snapshot_id: Option<i64>,
    /// Unix timestamp_ms at which this snapshot was created.
    pub last_updated_ms: i64,
    /// Table name.
    pub table_name: String,
    /// All data file entries covered by this snapshot.
    pub entries: Vec<DataFileEntry>,
    /// Arbitrary table properties (e.g. write.format.default = "VORTEX").
    pub properties: HashMap<String, String>,
}

impl IcebergExport {
    /// Build a fresh export from a table name and a snapshot ID.
    pub fn new(table_name: String, snapshot_id: i64) -> Self {
        Self {
            table_uuid: uuid::Uuid::new_v4().to_string().replace("-", ""),
            snapshot_id,
            sequence_number: 1,
            parent_snapshot_id: None,
            last_updated_ms: chrono::Utc::now().timestamp_millis(),
            table_name,
            entries: Vec::new(),
            properties: HashMap::new(),
        }
    }

    /// Append a data-file entry to this export and advance sequence number.
    pub fn add_entry(&mut self, entry: DataFileEntry) {
        self.entries.push(entry);
        self.sequence_number += 1;
    }

    /// Advance to a new snapshot (used when exporting a fresh snapshot).
    pub fn advance_snapshot(&mut self, new_snapshot_id: i64) {
        self.parent_snapshot_id = Some(self.snapshot_id);
        self.snapshot_id = new_snapshot_id;
        self.sequence_number = 1;
        self.last_updated_ms = chrono::Utc::now().timestamp_millis();
    }
}

/// A single data file referenced by an Iceberg manifest entry.
///
/// Corresponds to one column file in a RockDuck segment:
///   `{data_dir}/segments/{seg_id}/{col_name}.vortex`
///
/// All bounds are stored as raw byte vectors; the translation layer
/// (translate.rs) handles Iceberg-required hex-encoding and type-specific conversion.
#[derive(Debug, Clone, Serialize, Deserialize, Encode, Decode)]
pub struct DataFileEntry {
    /// Relative path from the Iceberg table root, e.g. "segments/seg_abc/id.vortex".
    pub file_path: String,
    /// Must be "VORTEX" to identify this as a Vortex (Arrow IPC) data file.
    pub file_format: String,
    /// Number of rows in this data file (from GranuleMeta.row_count).
    pub record_count: u64,
    /// File size in bytes (computed from actual disk stat).
    pub file_size: u64,
    /// Per-column lower-bound values, keyed by Iceberg field ID.
    /// Values are raw bytes (little-endian for primitive types).
    pub lower_bounds: HashMap<i32, Vec<u8>>,
    /// Per-column upper-bound values, keyed by Iceberg field ID.
    pub upper_bounds: HashMap<i32, Vec<u8>>,
    /// Per-column null counts, keyed by Iceberg field ID.
    pub null_counts: HashMap<i32, u64>,
    /// Byte offsets at which each granule starts within this file.
    /// Used by query engines for split planning (parallel reads).
    pub split_offsets: Vec<u64>,
    /// Optional sort order ID (defaults to DEFAULT_SORT_ORDER_ID).
    pub sort_order_id: i32,
}

impl DataFileEntry {
    /// Create a new entry for a Vortex column file.
    pub fn new(file_path: String, record_count: u64, file_size: u64) -> Self {
        Self {
            file_path,
            file_format: VORTEX_FORMAT.to_string(),
            record_count,
            file_size,
            lower_bounds: HashMap::new(),
            upper_bounds: HashMap::new(),
            null_counts: HashMap::new(),
            split_offsets: Vec::new(),
            sort_order_id: DEFAULT_SORT_ORDER_ID,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_iceberg_export_new_snapshot_id() {
        let manifest = IcebergExport::new("users".to_string(), 999);
        assert_eq!(manifest.snapshot_id, 999);
        assert_eq!(manifest.sequence_number, 1);
        assert!(manifest.parent_snapshot_id.is_none());
    }

    #[test]
    fn test_iceberg_export_add_entry_increments_sequence() {
        let mut manifest = IcebergExport::new("users".to_string(), 1);
        assert_eq!(manifest.sequence_number, 1);
        manifest.add_entry(DataFileEntry::new("a.vortex".into(), 10, 100));
        assert_eq!(manifest.sequence_number, 2);
        manifest.add_entry(DataFileEntry::new("b.vortex".into(), 20, 200));
        assert_eq!(manifest.sequence_number, 3);
    }

    #[test]
    fn test_iceberg_export_advance_snapshot() {
        let mut manifest = IcebergExport::new("users".to_string(), 1);
        manifest.advance_snapshot(2);
        assert_eq!(manifest.snapshot_id, 2);
        assert_eq!(manifest.parent_snapshot_id, Some(1));
        assert_eq!(manifest.sequence_number, 1);
    }

    #[test]
    fn test_iceberg_export_parent_snapshot_id_none_for_first() {
        let manifest = IcebergExport::new("users".to_string(), 1);
        assert!(manifest.parent_snapshot_id.is_none());
    }

    #[test]
    fn test_iceberg_export_parent_snapshot_id_set_after_advance() {
        let mut manifest = IcebergExport::new("users".to_string(), 1);
        manifest.advance_snapshot(5);
        assert_eq!(manifest.parent_snapshot_id, Some(1));
        assert_eq!(manifest.snapshot_id, 5);
        manifest.advance_snapshot(10);
        assert_eq!(manifest.parent_snapshot_id, Some(5));
        assert_eq!(manifest.snapshot_id, 10);
    }

    #[test]
    fn test_iceberg_export_advance_snapshot_resets_sequence() {
        let mut manifest = IcebergExport::new("users".to_string(), 1);
        manifest.add_entry(DataFileEntry::new("a.vortex".into(), 10, 100));
        assert_eq!(manifest.sequence_number, 2);
        manifest.advance_snapshot(2);
        assert_eq!(manifest.sequence_number, 1); // reset to 1 on advance
    }

    #[test]
    fn test_iceberg_export_entries_accumulate() {
        let mut manifest = IcebergExport::new("users".to_string(), 1);
        manifest.add_entry(DataFileEntry::new("seg1/col1.vortex".into(), 100, 1024));
        manifest.advance_snapshot(2);
        // advance_snapshot does NOT clear entries
        assert_eq!(manifest.entries.len(), 1);
        manifest.add_entry(DataFileEntry::new("seg2/col1.vortex".into(), 200, 2048));
        assert_eq!(manifest.entries.len(), 2);
    }

    #[test]
    fn test_data_file_entry_new_format_is_vortex() {
        let entry = DataFileEntry::new("x.vortex".into(), 0, 0);
        assert_eq!(entry.file_format, VORTEX_FORMAT);
        assert_eq!(entry.file_format, "VORTEX");
    }

    #[test]
    fn test_data_file_entry_preserves_all_fields() {
        let mut lower = HashMap::new();
        lower.insert(1, vec![0x00]);
        let mut upper = HashMap::new();
        upper.insert(1, vec![0xFF]);
        let mut nulls = HashMap::new();
        nulls.insert(1, 5u64);

        let mut entry = DataFileEntry::new("segments/seg1/id.vortex".into(), 1000, 8192);
        entry.lower_bounds = lower.clone();
        entry.upper_bounds = upper.clone();
        entry.null_counts = nulls.clone();
        entry.split_offsets = vec![0, 4096];
        entry.sort_order_id = 3;

        assert_eq!(entry.file_path, "segments/seg1/id.vortex");
        assert_eq!(entry.record_count, 1000);
        assert_eq!(entry.file_size, 8192);
        assert_eq!(entry.lower_bounds.get(&1), Some(&vec![0x00]));
        assert_eq!(entry.upper_bounds.get(&1), Some(&vec![0xFF]));
        assert_eq!(entry.null_counts.get(&1), Some(&5u64));
        assert_eq!(entry.split_offsets, &[0, 4096]);
        assert_eq!(entry.sort_order_id, 3);
    }
}
